# Generated by Django 2.2.4 on 2019-12-11 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoGuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=15, unique=True)),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('nuptk', models.CharField(max_length=15)),
                ('tanggal_lahir', models.DateField()),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=50)),
                ('status_aktif', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InfoSiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=15, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('tingkat_kelas', models.IntegerField(default=10)),
                ('tanggal_lahir', models.DateField()),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=50)),
                ('status_aktif', models.BooleanField()),
                ('jk', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jurusan', models.CharField(max_length=50)),
                ('nama_singkatan_jurusan', models.CharField(default='-', max_length=10)),
                ('status_aktif', models.IntegerField(default=1)),
                ('kepala_program', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.InfoGuru')),
            ],
        ),
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
                ('kkm', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NilaiUTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField()),
                ('mapel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.Mapel')),
                ('nis', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.InfoSiswa')),
            ],
        ),
        migrations.CreateModel(
            name='NilaiUAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField()),
                ('mapel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.Mapel')),
                ('nis', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.InfoSiswa')),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.IntegerField(default=10)),
                ('jurusan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.Jurusan')),
                ('nip_wali_kelas', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.InfoGuru')),
                ('nis_ketua_kelas', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ketua_kelas', to='SCOM_APP.InfoSiswa')),
                ('nis_wakil_ketua_kelas', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wakil_ketua_kelas', to='SCOM_APP.InfoSiswa')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalGuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.IntegerField(default=10)),
                ('mulai_belajar', models.TimeField()),
                ('berhenti_belajar', models.TimeField()),
                ('jurusan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.Jurusan')),
                ('mapel', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SCOM_APP.Mapel')),
                ('nip', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SCOM_APP.InfoGuru')),
            ],
        ),
        migrations.AddField(
            model_name='infosiswa',
            name='jurusan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.Jurusan'),
        ),
    ]
