# Generated by Django 2.2.4 on 2019-11-11 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisKelamin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jurusan', models.CharField(max_length=50)),
                ('nip_kepala_program', models.IntegerField(default=0)),
                ('status_aktif', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
                ('kkm', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NilaiUTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.IntegerField(default=0)),
                ('nilai', models.DecimalField(decimal_places=3, max_digits=5, max_length=11)),
                ('mapel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.Mapel')),
            ],
        ),
        migrations.CreateModel(
            name='NilaiUAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.IntegerField(default=0)),
                ('nilai', models.DecimalField(decimal_places=3, max_digits=5, max_length=11)),
                ('mapel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.Mapel')),
            ],
        ),
        migrations.CreateModel(
            name='MapelGuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.IntegerField(default=0)),
                ('mapel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.Mapel')),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip_wali_kelas', models.IntegerField(default=0)),
                ('nis_ketua_kelas', models.IntegerField(default=0)),
                ('nis_wakil_ketua_kelas', models.IntegerField(default=0)),
                ('jurusan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.Jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalGuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mulai_belajar', models.TimeField()),
                ('berhenti_belajar', models.TimeField()),
                ('kelas', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.Kelas')),
                ('mapel_guru', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.MapelGuru')),
            ],
        ),
        migrations.CreateModel(
            name='InfoSiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.IntegerField(default=0)),
                ('nama', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=50)),
                ('status_aktif', models.BooleanField()),
                ('jk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.JenisKelamin')),
                ('kelas', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.Kelas')),
            ],
        ),
        migrations.CreateModel(
            name='InfoGuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.IntegerField(default=0)),
                ('nama', models.CharField(max_length=50)),
                ('nuptk', models.IntegerField(default=0)),
                ('tanggal_lahir', models.DateField()),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=50)),
                ('status_aktif', models.BooleanField()),
                ('jurusan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.Jurusan')),
            ],
        ),
    ]
