# Generated by Django 2.2.4 on 2019-11-11 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCOM_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='jurusan',
        ),
    ]
