# Generated by Django 2.2.4 on 2019-11-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCOM_APP', '0002_remove_kelas_jurusan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoguru',
            name='jurusan',
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='nis_ketua_kelas',
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='nis_wakil_ketua_kelas',
        ),
        migrations.AddField(
            model_name='infosiswa',
            name='jurusan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.Jurusan'),
        ),
        migrations.AlterField(
            model_name='infosiswa',
            name='jk',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jurusan',
            name='nip_kepala_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.InfoGuru'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='nip_wali_kelas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.InfoGuru'),
        ),
        migrations.AlterField(
            model_name='nilaiuas',
            name='nis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.InfoSiswa'),
        ),
        migrations.AlterField(
            model_name='nilaiuts',
            name='nis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.InfoSiswa'),
        ),
        migrations.DeleteModel(
            name='JenisKelamin',
        ),
    ]
