# Generated by Django 2.2.4 on 2019-11-11 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCOM_APP', '0003_auto_20191111_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infosiswa',
            name='kelas',
        ),
        migrations.AddField(
            model_name='infosiswa',
            name='tingkat_kelas',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='kelas',
            name='jurusan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCOM_APP.Jurusan'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='nis_ketua_kelas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ketua_kelas', to='SCOM_APP.InfoSiswa'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='nis_wakil_ketua_kelas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wakil_ketua_kelas', to='SCOM_APP.InfoSiswa'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='tingkat',
            field=models.IntegerField(default=10),
        ),
    ]
