# Generated by Django 2.2.4 on 2019-11-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOM_APP', '0004_auto_20191111_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurusan',
            name='nama_singkatan_jurusan',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
