# Generated by Django 2.2.4 on 2019-11-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOM_APP', '0005_jurusan_nama_singkatan_jurusan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoguru',
            name='nip',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='infoguru',
            name='nuptk',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='infosiswa',
            name='nis',
            field=models.CharField(max_length=15),
        ),
    ]
