# Generated by Django 2.2.4 on 2019-11-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCOM_APP', '0006_auto_20191111_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jurusan',
            old_name='nip_kepala_program',
            new_name='kepala_program',
        ),
    ]
